### PR TITLE
Add ssh keys to fury kubernetes on premise

### PR DESCRIPTION
**Pull request by errorhead**
Update with our ssh keys

### CODE REVIEW

**Comment by bernardhalas** [comment]
> _No description provided._

Please always provide at least some basic description, let's not cut corners, we're not in a rush.
Should we also update `/roles/sighup-base/vars/main.yml`?

**Comment by angelbarrera92** [comment]
> I see you're removing the usage of Giacomo's key from `main.yml`... perhaps we might as well delete his key file. Or he should be put into the blacklist? I don't know..
> What do you guys think @bernardhalas @phisco @angelbarrera92 ?
> 
> Anyway, LGTM apart from my point above

Should be enough removing it.

**Comment by bernardhalas** [comment]
If we want to remove user from our infrastructure, it needs to be put into the `blacklist` variable. Otherwise it will be ignored and not removed.

```- name: Removing users not part of the team anymore
  become: true
  user:
    name: "{{ item.key }}"
    state: absent
  with_dict: "{{ blacklist }}"
```

**Comment by errorhead** [comment]
> If we want to remove user from our infrastructure, it needs to be put into the `blacklist` variable. Otherwise it will be ignored and not removed.
> 
> File `vendor/roles/on-premise/sighup-base/tasks/users.yml`:
> 
> ```
>  19 - name: Removing users not part of the team anymore
>  20   become: true
>  21   user:
>  22     name: "{{ item.key }}"
>  23     state: absent
>  24   with_dict: "{{ blacklist }}"
> ```

I did new commit for blacklisted user. Thank you.

**Pull request merged**
